import React, { useEffect, useState } from "react";
import Head from "next/head";
import Breadcrumb from "./Breadcrumb";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";
import axios from 'axios';


const Layout = ({
    children,
    parent,
    sub,
    subChild,
    noBreadcrumb,
    headerStyle,
}) => {
    const [isToggled, setToggled] = useState(false);
    const [fetchData, setFetchData] = useState(false);

    const toggleClick = () => {
        setToggled(!isToggled);
        isToggled
            ? document
                  .querySelector("body")
                  .classList.remove("mobile-menu-active")
            : document
                  .querySelector("body")
                  .classList.add("mobile-menu-active");
    };

    const dataFetch = () => {
        axios.get('http://localhost:4000/testing')
        .then(res => setFetchData(res.data))
        .catch(err => console.log(err))
    }
    
    useEffect(() => {
        dataFetch()
    }, [])

    return (
        
        <>
            <Head>
                <title>Dreamy cake</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/theme/favicon-2.svg" />
            </Head>

            {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>}

            <Header headerStyle={headerStyle} isToggled={isToggled} toggleClick={toggleClick} />
            <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />
            <main className="main">
                <Breadcrumb parent={parent} sub={sub} subChild={subChild} noBreadcrumb={noBreadcrumb} />
                {
                    fetchData && 
                    fetchData.map(data => {
                        return (
                            <p>{data.name}</p>
                        )
                    })
                }
                {children}
            </main>
            <Footer />
        </>
    );
};

export default Layout;
